// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.BingoCardGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("card")]
        public Card[][] Card { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("size")]
        public long Size { get; set; }

        [JsonProperty("freeSpace")]
        public bool FreeSpace { get; set; }

        [JsonProperty("totalCells")]
        public long TotalCells { get; set; }

        [JsonProperty("winningPatterns")]
        public string[] WinningPatterns { get; set; }

        [JsonProperty("image")]
        public Image Image { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("imageName")]
        public string ImageName { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }
    }

    public partial struct Card
    {
        public long? Integer;
        public string String;

        public static implicit operator Card(long Integer) => new Card { Integer = Integer };
        public static implicit operator Card(string String) => new Card { String = String };
    }
}
